services:
  ciberpizza:
    container_name: ciberpizza
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    container_name: mysql
    image: mysql:8.3
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - ciberpizza

volumes:
  mysql-data:
